version: '3.7'
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: zbxgrafana
    restart: always
    ports:
      - "38000:3000"
    env_file:
      - ./config/env_grafana
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./plugins:/var/lib/grafana/plugins      
    healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep grafana || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    networks:
      - zbx
  grafanadb:
    image: postgres:latest
    container_name: zbxgrafanadb
    restart: always
    env_file:
      - ./config/env_dbgrafana
    secrets:
      - grafana_db_user
      - grafana_db_pass
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 20s
      timeout: 10s
      retries: 2
      start_period: 5s
    networks:
      - zbx
volumes:
  postgres-data: {}
  grafana-data: {}
networks:
  zbx:
    external: true
secrets:
  grafana_db_user:
    file: ./config/.grafana_db_user
  grafana_db_pass:
    file: ./config/.grafana_db_pass
